heetch/avro

analyze.go, avro-generate-go/generate.go, avro-generate-go/template.go, decode.go, encode.go, go.mod, go.sum, gotype.go, type.go
[This issue](https://github.com/actgardner/gogen-avro/issues/119) makes it hard to use avrogen the way we want to, and it's not clear how long it might take to merge the fix, so for the time being let's use a forked version.
The module involved isn't exposed at all in the public API so this is a backwardly compatible change, and it'll be backwardly compatible to revert it too.
=> use avrogen fork

analyze.go, decode.go, encode.go, gotype.go, names.go, names_test.go, singledecoder.go, singledecoder_test.go, singleencoder.go, singleencoder_test.go, type.go
This adds the capability to change the names in Avro schemas.
This can be used to change the automatically assigned names
given to schemas derived from Go types, for example.
=> namespace support

avro-generate-go/generatetestcode.go, avro-generate-go/internal/avrotestdata/testdata.go, avro-generate-go/testdata/cloudevent.cue, avro-generate-go/testdata/default.cue, avro-generate-go/testdata/gotype.cue, avro-generate-go/testdata/logicaltype.cue, avro-generate-go/testdata/record.cue, avro-generate-go/testdata/testschema.cue, avro-generate-go/testdata/union.cue, avro-generate-go/verify_test.go
This allows us to verify the Go Avro behaviour against
the canonical Java implementation (and potentially other
implementations too).
We fix the tests that require fixing because of this.
The script I've been using for AVRO_VERIFY is this:
#!/usr/bin/env rc
if(! ~ $#* 3) {
echo usage: avroverify in-schema out-schema in-data >[1=2]
exit 1
}
inSchema=$1
outSchema=$2
inData=$3
dir=`{mktemp -d}
if (! echo $inData | avro fromjson --schema $inSchema - > $dir/data.out) {
echo fromjson failed >[1=2]
exit 1
}
if (! avro tojson --reader-schema $outSchema $dir/data.out) {
echo tojson failed >[1=2]
exit 1
}
rm -r $dir
where the `avro` command is itself a wrapper around the `avro-tools.jar` file:
java \
'-Dlog4j.configuration=file://'^<{echo 'log4j.rootLogger=off'} \
--add-opens …
=> support external verification of round trip tests

cmd/avro-generate-go/generatetestcode.go, cmd/avro-generate-go/internal/avrotestdata/testdata.go, cmd/avro-generate-go/internal/generated_tests/enumDefault/schema_gen.go, cmd/avro-generate-go/internal/generated_tests/simpleEnum/other_test.go, cmd/avro-generate-go/internal/generated_tests/simpleEnum/schema_gen.go, cmd/avro-generate-go/internal/testutil/generatetest.go, cmd/avro-generate-go/main.go, cmd/avro-generate-go/template.go, cmd/avro-generate-go/testdata/enum.cue, cmd/avro-generate-go/testdata/testschema.cue
This means that generated enums can function better when
marshaled to JSON.
Fixes #12.
=> cmd/avro-generate-go: implement String etc methods for enums

cmd/avro-generate-go/internal/generated_tests/cloudEvent/roundtrip_test.go, cmd/avro-generate-go/internal/generated_tests/cloudEvent/schema.avsc, cmd/avro-generate-go/internal/generated_tests/cloudEvent/schema_gen.go, cmd/avro-generate-go/testdata/cloudevent.cue, go.mod, go.sum
This allows us to read a record without using the same name
when reading it, which matches the Java implementation and
means we can go with our current plan for encoding CloudEvent
metadata inside Kafka messages.
Note: this is reliant on the relevant update to the forked version of gogen-avro.
=> allow different names in non-union references

analyze.go, bench_test.go, decode.go, go.sum, gotype_test.go, reader.go, singledecoder.go, typeinfo.go
Also speed up SingleDecoder a lot (we'd forgotten to cache
the compile results) and unmarshaling in general (the debugf
calls were really slowing things down).
Here are the new benchmark results after these changes have been
made:
```
BenchmarkMarshal-4                  	10628875	       551 ns/op	     240 B/op	       4 allocs/op
BenchmarkSingleDecoderUnmarshal-4   	 3596359	      1619 ns/op	     272 B/op	      14 allocs/op
```
=> fix Unmarshal buffer corruption

encode.go, names.go
We'd like to provide the possibility to pair the encoding for a top level
type with a chosen schema.  That means we can't assume there's always
a specific association between Go type and Avro encoder for that type,
so we want to remove the use of the global cache in the body of the
encoder builder.
This is the first step towards allowing external definitions in generated
schema code.
This code doesn't change any externally-visible semantics.
=> avro: cache type encoders at top level only

cmd/avro-generate-go/generate_test.go, cmd/avro-generate-go/main.go, singledecoder_test.go
Given that avro-generate-go is conventionally invoked in
a `go generate` context and thus is provided with `$GOPACKAGE`
and `$GOFILE` environment variables, we can make a better
guess about the likely values for the `-p` and `-t` flags, so do that.
=> cmd/avro-generate-go: use better defaults for flags

avroregistry/message.go, avroregistry/registry.go, avroregistry/registry_test.go
This means that we can use the same registry for
many different subjects, which maps better to
how the registry API actually works underneath,
and how we want to use the API.
=> avroregistry: return separate codec types

singleencoder.go, singleencoder_test.go
This will make only a single call to the registry for a given type.
Also add a `CheckMarshalType` method that can be used to check
that a type is OK with a `SingleEncoder` and also populate the
cache in advance.
=> avro: more efficient SingleEncoder

type.go, type_test.go
Because of https://github.com/confluentinc/schema-registry/issues/1348, we
need to be sure that schemas added to the registry and searched in the registry
don't have extra metadata that can cause the search to fail.
To do that, we implement the canonical parsing normalization as specified
in the [Avro spec](https://avro.apache.org/docs/1.9.1/spec.html#Transforming+into+Parsing+Canonical+Form), with the addition that defaults can also be retained.
=> avro: add CanonicalString method

avroregistry/message.go, avroregistry/registry.go, avroregistry/registry_test.go, bench_test.go, singledecoder.go, singledecoder_test.go, singleencoder.go, singleencoder_test.go, type_test.go
As this means that the registry needs to use the `CanonicalString` method,
we want to avoid the extra round-trip through `ParseType`, so we change
the signature of the `EncodingRegistry` interface so that it takes
a `*avro.Type` rather than a string, and we also make a similar
change in `DecodingRegistry` for consistency.
This works around this bug in the Schema registry: https://github.com/confluentinc/schema-registry/issues/1348
=> avroregistry: canonicalize schemas when registering and getting

type.go, type_test.go
Calculating a canonical string is a bit costly, so make sure we
only do it once for a given type.
=> avro: more efficient CanonicalString

avroregistry/registry.go
Add Content-Type to doRequest to prevent HTTP 415 errors
=> Add Content-Type to doRequest

avroregistry/message.go, avroregistry/registry.go, avroregistry/registry_test.go, type.go, type_test.go
Use this functionality to retain logical types in the schemas
stored in the registry. This means that we'll be able to do
schema-resolution checks that logical types haven't inappropriately
changed (for example that the scale on a decimal value is the same)
or generate appropriate conversion code.
Somewhat gratuitously (but it's very early days, so hopefully OK)
we change the naming of the canonicalization constants to use
a `Retain` prefix instead of `Leave`, as that seems less ambiguous.
=> allow retaining logical types in CanonicalString

cmd/avrogo/externaltype.go, cmd/avrogo/main.go, cmd/avrogo/outputpath_test.go, cmd/avrogo/script_test.go, cmd/avrogo/testdata/script/non-existent-output-dir.txt, cmd/avrogo/testdata/script/relativedir.txt, cmd/go2avro/testdata/simple.txt
We fix an issue where a relative path passed as argument to the `-d`
flag would cause `avrogo` to report that the file doesn't exist,
and we also implement an algorithm to calculate unambiguous
output file names when passed several schema files with the same
base file name in almost all cases.
We also create the output directory if it doesn't already exist.
=> cmd/avrogo: fix output file names

cmd/avrogo/doccomment_test.go, cmd/avrogo/generate.go, cmd/avrogo/internal/generated_tests/cloudEvent/roundtrip_test.go, cmd/avrogo/internal/generated_tests/cloudEvent/schema.avsc, cmd/avrogo/internal/generated_tests/cloudEvent/schema_gen.go, cmd/avrogo/internal/generated_tests/largeRecord/roundtrip_test.go, cmd/avrogo/internal/generated_tests/largeRecord/schema.avsc, cmd/avrogo/template.go, cmd/avrogo/testdata/cloudevent.cue
The IDL spec says:
> Comments that begin with /** are used as the documentation string for the type or field definition that follows the comment.
The idl2schemata tool takes that literally and includes all the comment
text including the leading `*`. This doesn't look nice when converted
to a Go doc comment, so remove the stars.
=> cmd/avrogo: better handling of IDL comments

avroregistry/registry_test.go, cmd/avrogo/internal/generated_tests/cloudEvent/roundtrip_test.go, type.go, type_test.go
We were omitting the `fields` member when there were
no fields rather than including an empty array.
=> avro: fix canonicalization

cmd/avsc2avdl/main.go, cmd/avsc2avdl/script_test.go, cmd/avsc2avdl/testdata/enumwarning.txt, cmd/avsc2avdl/testdata/recordwarning.txt, cmd/avsc2avdl/testdata/simple.txt, decode.go, gotype.go
This command converts from the [AVSC format](https://avro.apache.org/docs/1.9.1/spec.html)
to the [IDL format](https://avro.apache.org/docs/current/idl.html).
Also add a couple of unrelated comments on avro encoding internals
prompted by a code walkthrough.
=> cmd/avsc2avdl: new command

avroregistrytest/avroregistrytest.go
I got a subject deletion error because in a `main_test` I registered all topics and forgot that the `kafkatest` producer (from another repo) also registers the topic of the message it produces. So one topic was registered twice (no issue), and because of the `t.Cleanup` also cleaned up twice => First delete works, second one doesn't 💥  and with that the whole test is marked as failed.
Not knowing which topic caused the issue made debugging harder. So here I propose to include the topic in the error message. Also the `%w` was misused: It's only supported in `fmt.Errorf` for _creating a new error_, not in `t.Errorf`, which doesn't create a new error.
Old error: `cannot delete subject: %!w(*avroregistry.apiError=&{40401 Subject not found. 404})`
New error: `cannot delete subject foo.bar.v0: …
=> Improve subject deletion error message

avroregistry/message.go, avroregistry/registry.go, avroregistry/registry_test.go
This PR implements `GET /subjects/{subject}/versions/{version}`.
See https://docs.confluent.io/platform/current/schema-registry/develop/api.html#get--subjects-(string-%20subject)-versions-(versionId-%20version)
for details.
It also fixes registry tests to be run in CI and other minor fixes
after deprecating Go versions lower than 1.15.
=> Add avroregistry.Schema

README.md, analyze.go, cmd/avrogo/generate.go, cmd/avrogo/testdata/logicaltype.cue, cue.mod/pkg/github.com/heetch/cue-schema/avro/schema.cue, decode.go, encode.go, gotype.go, gotype_test.go
This PR extends support for `time.Duration` converting from/to Avro using a
logical type that we have defined `duration-nanos` as @rogpeppe suggested in
https://github.com/heetch/avro/issues/3#issuecomment-578120531.
`time.Duration` <=> `{"type": {"type": "long", "logicalType": "duration-nanos"}}}`
=> Add logicalType "duration-nanos"

decode.go, gotype_test.go
As we do in UUID encoding https://github.com/heetch/avro/blob/master/encode.go#L278-L279.
For the cases, we are encoding zero UUID, we sending to the wire "" 
so the decoding should behave the same way to hold a zero value in this case too.
=> Allow UUID empty string decoding as empty UUID object

.github/workflows/test.yaml, go.mod, go.sum
Go 1.15 is more than 2 years old so we can drop it.
And include go1.18 and go1.19.
=> Remove go1.15 and add go1.18 and go1.19

avroregistry/errors.go, avroregistry/errors_test.go, avroregistry/registry.go, avroregistry/registry_test.go, singledecoder.go
Return a specific error that can be used to detect when the schema registry is unavailable. This means that, for example, number one can retry indefinitely in case such an error is encountered so as not to skip messages when consuming but otherwise respect a limited retry mechanism that might be in place. 
Instead of trying to check all the net.Error, url.Error or syscall.ECONNREFUSED, the logic has simply been reduced to "in case there is an error during performing the request and we have no more retries left then the registry is not available". This means that, even if we have consecutive timeouts that exceed the retry limit for operations will be considered as the schema registry is not available.
=> BCN-458 handle specific decoding error when schema registry unavailable
